local utils = require("utils")
local map = utils.map
local nnoremap = utils.nnoremap
local inoremap = utils.inoremap
local tnoremap = utils.tnoremap
map("<space>", "<leader>")
nnoremap("Y", "y$")
nnoremap("U", "<c-r>")
nnoremap("`", "'")
nnoremap("'", "`")
nnoremap("<leader>+", ":lua SetFontSize(1)")
nnoremap("<leader>-", ":lua SetFontSize(-1)")
nnoremap("<leader>w", ":sil make<enter>")
inoremap("<c-h>", "b")
inoremap("<c-l>", "E<c-o>l")
nnoremap("<c-h>", "<c-w>W")
nnoremap("<c-l>", "<c-w>w")
nnoremap("<c-b>", ":b#<enter>")
nnoremap("<c-j>", ":bprev<enter>")
nnoremap("<c-k>", ":bnext<enter>")
nnoremap("<c-t>", ":tabedit %<enter>")
nnoremap("<c-f>", ":lcd %:p:h<enter>:pwd<enter>")
nnoremap("<c-g>", ":GT<enter>:pwd<enter>")
nnoremap("<leader>zfi", ":set foldmethod=indent<enter>")
nnoremap("<leader>zfm", ":set foldmethod=manual<enter>")
nnoremap("<leader>n", ":cnext<enter>")
nnoremap("<leader>p", ":cprev<enter>")
nnoremap("<leader>t", ":NvimTreeToggle<enter>")
nnoremap("<leader>T", ":NvimTreeFindFile<enter>")
tnoremap("<C-[>", "<C-\\><C-n>")
tnoremap("<c-h>", "<C-\\><C-n><c-w>W")
return tnoremap("<c-l>", "<C-\\><C-n><c-w>w")
